server:
  port: 2000
  max-http-header-size: 20480

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: storeservice
  datasource:
    url: jdbc:mysql://localhost:3306/UserCenter?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1000/eureka/

storeservice:
  ribbon:
    MaxAutoRetries: 2
    ConnectTimeout: 30000
    ReadTimeout: 30000