server:
  port: 4000

spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: recommendservice

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1000/eureka/

recommendservice:
  ribbon:
    MaxAutoRetries: 2
    ConnectTimeout: 30000
    ReadTimeout: 30000