server:
  port: 3000

spring:
  application:
    name: storeservice
  cloud:
    loadbalancer:
      retry:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/FeedBack?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1000/eureka/